#!/usr/bin/env python3
"""Stage and verify the complete, relocatable macOS WebKit build products."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import plistlib
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent.parent
REPOSITORY = "https://github.com/QuartzBrowser/WebKit.git"
MANIFEST = "QuartzWebKit.json"
MANAGED_MARKER = ".quartz-webkit-products"
REQUIRED = ("WebKit.framework", "JavaScriptCore.framework", "WebCore.framework")
MAGICS = (b"\xfe\xed\xfa\xce", b"\xce\xfa\xed\xfe", b"\xfe\xed\xfa\xcf", b"\xcf\xfa\xed\xfe", b"\xca\xfe\xba\xbe", b"\xbe\xba\xfe\xca", b"\xca\xfe\xba\xbf")


def run(*args):
    return subprocess.check_output([str(arg) for arg in args], text=True).strip()


def macho_files(directory):
    for path in sorted(directory.rglob("*")):
        if path.is_file() and not path.is_symlink():
            with path.open("rb") as stream:
                if stream.read(4) in MAGICS:
                    yield path


def dependencies(path):
    return re.findall(r"^\s+(.+?) \(compatibility version", run("otool", "-L", path), re.M)


def install_ids(path):
    return [line.strip() for line in run("otool", "-D", path).splitlines()
            if line.strip() and not line.endswith(":")]


def rpaths(path):
    return re.findall(r"cmd LC_RPATH\s+cmdsize \d+\s+path (.+?) \(offset", run("otool", "-l", path))


def architecture_set(path):
    return set(run("lipo", "-archs", path).split())


def version_tuple(value):
    return tuple(int(part) for part in value.split(".")) + (0,) * (3 - len(value.split(".")))


def minimum_version(paths):
    versions = []
    for path in paths:
        commands = run("otool", "-l", path)
        versions += re.findall(r"\bminos (\d+\.\d+(?:\.\d+)?)", commands)
        versions += re.findall(r"cmd LC_VERSION_MIN_MACOSX\s+cmdsize \d+\s+version (\d+\.\d+(?:\.\d+)?)", commands)
    if not versions:
        raise ValueError("No macOS deployment target found in WebKit binaries")
    return max(versions, key=version_tuple)


def digest(path):
    hasher = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            hasher.update(block)
    return hasher.hexdigest()


def check_output(directory):
    if not directory.exists():
        return
    if not directory.is_dir() or directory.is_symlink():
        raise ValueError(f"WebKit output is not an ordinary directory: {directory}")
    if not any(directory.iterdir()):
        return
    marker = directory / MANAGED_MARKER
    if not marker.is_file() or marker.read_text() != "Generated by Quartz build-webkit.sh\n":
        raise ValueError(f"Refusing to replace an existing unmanaged directory: {directory}")
    info = json.loads((directory / MANIFEST).read_text())
    allowed = {*info["products"], MANAGED_MARKER, MANIFEST, "WebKit-Licenses"}
    if info["repository"] != REPOSITORY or {path.name for path in directory.iterdir()} - allowed:
        raise ValueError(f"WebKit output contains unrelated files: {directory}")


def normalize_webcore_frameworks_link(directory):
    # WebCore's "Make Frameworks Symbolic Link" phase also runs for Release,
    # where ANGLE/libwebrtc are sibling dylibs rather than installed here.
    # Remove only that unused alias from our copy; all code links stay strict.
    framework = directory / "WebCore.framework"
    versions = framework / "Versions"
    current = versions / "Current"
    version = versions / "A"
    link = framework / "Frameworks"
    target = version / "Frameworks"
    if (all(path.is_dir() and not path.is_symlink() for path in (framework, versions, version))
            and current.is_symlink() and os.readlink(current) == "A"
            and link.is_symlink() and os.readlink(link) == "Versions/Current/Frameworks"
            and not target.exists() and not target.is_symlink()):
        link.unlink()


def check_symlinks(directory):
    for path in directory.rglob("*"):
        if path.is_symlink():
            resolved = path.resolve(strict=True)
            if not resolved.is_relative_to(directory.resolve()):
                raise ValueError(f"WebKit symlink escapes its products directory: {path}")


def dependency_map(directory):
    result = {}
    for path in macho_files(directory):
        ids = install_ids(path)
        if not ids:
            continue
        replacement = "@rpath/" + str(path.relative_to(directory))
        for key in [path.name, *ids]:
            if key in result and result[key] != replacement:
                raise ValueError(f"Ambiguous WebKit library: {key}")
            result[key] = replacement
    return result


def relocate(path, directory, mapping, set_id=False, final_path=None):
    final_path = final_path or path
    archs = sorted(architecture_set(path))
    if len(archs) == 1:
        relocate_image(path, final_path, directory, mapping, set_id)
        return
    # install_name_tool requires a deleted rpath to exist in every slice. Build
    # paths can differ between architectures, so edit each slice independently.
    with tempfile.TemporaryDirectory(prefix="webkit-relocate-") as temporary:
        slices = []
        for arch in archs:
            image = Path(temporary) / arch
            run("lipo", path, "-thin", arch, "-output", image)
            relocate_image(image, final_path, directory, mapping, set_id)
            slices.append(image)
        merged = Path(temporary) / "universal"
        run("lipo", "-create", *slices, "-output", merged)
        # Keep the original executable permissions and other destination metadata.
        shutil.copyfile(merged, path)


def relocate_image(image, final_path, directory, mapping, set_id):
    changes = []
    if set_id and install_ids(image):
        changes += ["-id", "@rpath/" + str(final_path.relative_to(directory))]
    for dependency in set(dependencies(image)):
        replacement = mapping.get(dependency) or mapping.get(Path(dependency).name)
        if replacement and dependency != replacement:
            changes += ["-change", dependency, replacement]
    # Every helper has its own path to the flat framework directory. This keeps
    # WebKit's original sibling XPC symlinks and staged dyld paths working.
    relative = os.path.relpath(directory, final_path.parent)
    local_rpath = "@loader_path" + ("/" + relative if relative != "." else "")
    existing = set(rpaths(image))
    for old in existing:
        if old.startswith("/") and not old.startswith(("/System/Library/", "/usr/lib/")):
            changes += ["-delete_rpath", old]
    if local_rpath not in existing:
        changes += ["-add_rpath", local_rpath]
    if changes:
        subprocess.run(["install_name_tool", *changes, str(image)], check=True)


def sign(directory, identity="-", manifest=None):
    directory = directory.resolve()
    info = None
    if manifest is not None:
        if manifest.is_symlink():
            raise ValueError("Refusing to rewrite a symlinked WebKit signing manifest")
        info = json.loads(manifest.read_text())
        if info["repository"] != REPOSITORY:
            raise ValueError("Unexpected repository in WebKit signing manifest")
        # Sparkle is separately packaged and must never join the engine hashes.
        verified_binaries(directory, info, excluded_products=("Sparkle.framework",))
    flags = ["--force", "--sign", identity]
    if identity != "-":
        flags += ["--options", "runtime", "--timestamp"]
    # Read each executable's original entitlements before replacing its signature.
    # WebContent's JIT/sandbox rights differ from Networking/GPU and Sparkle.
    for path in macho_files(directory):
        result = subprocess.run(["codesign", "-d", "--entitlements", ":-", str(path)], capture_output=True)
        entitlements = {}
        if result.stdout.strip():
            entitlements = plistlib.loads(result.stdout)
        entitlements.pop("com.apple.security.get-task-allow", None)
        with tempfile.NamedTemporaryFile(suffix=".plist") as output:
            plistlib.dump(entitlements, output)
            output.flush()
            extra = ["--entitlements", output.name] if entitlements else []
            subprocess.run(["codesign", *flags, *extra, str(path)], check=True)
    # Seal nested services/apps before their containing framework (Sparkle has
    # an Updater.app in addition to XPC services).
    bundles = [path for path in directory.rglob("*")
               if path.suffix in (".xpc", ".app", ".framework") and path.is_dir() and not path.is_symlink()]
    for path in sorted(bundles, key=lambda item: len(item.parts), reverse=True):
        subprocess.run(["codesign", *flags, "--preserve-metadata=entitlements", str(path)], check=True)
    if info is not None:
        info["sha256"] = {relative: digest(directory / relative) for relative in info["sha256"]}
        # This updates the app's copy after signing; prepared products keep their
        # original signatures and hashes for subsequent builds.
        manifest.write_text(json.dumps(info, indent=2) + "\n")


def verify_links(directory, paths):
    known = dependency_map(directory)
    for path in paths:
        for dependency in dependencies(path):
            local = known.get(dependency) or known.get(Path(dependency).name)
            if local:
                if dependency != local:
                    raise ValueError(f"Unrelocated WebKit dependency in {path}: {dependency}")
                if not (directory / dependency.removeprefix("@rpath/")).is_file():
                    raise ValueError(f"Missing embedded dependency: {dependency}")
            elif not dependency.startswith(("/System/Library/", "/usr/lib/")):
                # No external build paths or unresolved third party @rpath libs.
                raise ValueError(f"Unbundled dependency in {path}: {dependency}")
            elif any(name in dependency for name in REQUIRED):
                raise ValueError(f"System WebKit dependency in {path}: {dependency}")


def verified_binaries(directory, info, excluded_products=()):
    binaries = [path for path in macho_files(directory)
                if path.relative_to(directory).parts[0] not in excluded_products]
    for name in REQUIRED:
        if (directory / name / name.removesuffix(".framework")).resolve() not in binaries:
            raise ValueError(f"Missing {name}; run Scripts/build-webkit.sh")
    if not isinstance(info["products"], list) or not info["products"]:
        raise ValueError("Empty WebKit product inventory")
    if len(info["products"]) != len(set(info["products"])):
        raise ValueError("Duplicate WebKit products")
    for name in info["products"]:
        if not isinstance(name, str) or name in excluded_products or Path(name).name != name or Path(name).suffix not in (".framework", ".xpc", ".dylib") or not (directory / name).exists():
            raise ValueError(f"Invalid WebKit product name: {name}")
    if not set(REQUIRED).issubset(info["products"]) or any(path.relative_to(directory).parts[0] not in info["products"] for path in binaries):
        raise ValueError("Incomplete WebKit product inventory")
    for relative, expected in info["sha256"].items():
        path = directory / relative
        if not path.resolve().is_relative_to(directory) or digest(path) != expected:
            raise ValueError(f"WebKit product hash mismatch: {relative}")
    if set(info["sha256"]) != {str(path.relative_to(directory)) for path in binaries}:
        raise ValueError("WebKit binary inventory differs from the build manifest")
    check_symlinks(directory)
    return binaries


def validate(directory, lock_file=ROOT / "WebKit.lock.json", archs=(), manifest=None, excluded_products=()):
    directory = directory.resolve()
    info = json.loads((manifest or directory / MANIFEST).read_text())
    lock = json.loads(lock_file.read_text())
    if info["repository"] != REPOSITORY or info["repository"] != lock["repository"] or info["revision"] != lock["revision"]:
        raise ValueError("WebKit products do not match WebKit.lock.json; rebuild the pinned fork")
    if info.get("macOSDeploymentTarget") != lock["macOSDeploymentTarget"]:
        raise ValueError("WebKit macOSDeploymentTarget does not match WebKit.lock.json; rebuild the pinned fork")
    binaries = verified_binaries(directory, info, excluded_products)
    if info["minimumSystemVersion"] != minimum_version(binaries):
        raise ValueError("WebKit minimumSystemVersion does not match its binaries")
    if set(info["architectures"]) != set.intersection(*(architecture_set(path) for path in binaries)):
        raise ValueError("WebKit architecture manifest does not match its binaries")
    for path in binaries:
        if not set(archs).issubset(architecture_set(path)):
            raise ValueError(f"{path} is missing requested architectures {archs}")
    verify_links(directory, binaries)
    return info


def prepare_sparkle(args):
    source = args.source_framework.resolve(strict=True)
    output = args.output_dir.resolve()
    destination = output / "Sparkle.framework"
    if source.name != "Sparkle.framework" or not source.is_dir():
        raise ValueError("Expected an original Sparkle.framework source directory")
    # Do not resolve the destination itself: SwiftPM may make it a symlink to
    # the downloaded artifact, which must be replaced without touching its target.
    if destination.is_relative_to(source) or source.is_relative_to(destination):
        raise ValueError("Sparkle output must not overlap its original source")
    system = getattr(args, "system", False)
    products = None if system else args.products_dir.resolve()
    if products is not None:
        info = validate(products, manifest=args.manifest, excluded_products=("Sparkle.framework",))
        mapping = {key: value for key, value in dependency_map(products).items()
                   if value.removeprefix("@rpath/").split("/")[0] in info["products"]}
    output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".quartz-sparkle-", dir=output) as temporary:
        stage = Path(temporary)
        framework = stage / "Sparkle.framework"
        shutil.copytree(source, framework, symlinks=True)
        for path in framework.rglob("*"):
            if not system and path.is_symlink() and os.path.isabs(os.readlink(path)):
                target = Path(os.readlink(path))
                if not target.is_relative_to(source):
                    raise ValueError(f"External Sparkle source symlink: {path} -> {target}")
                path.unlink()
                path.symlink_to(os.path.relpath(framework / target.relative_to(source), path.parent))
        check_symlinks(framework)
        binaries = list(macho_files(framework))
        if (framework / "Sparkle").resolve() not in binaries:
            raise ValueError("Missing Sparkle framework executable")
        if products is not None:
            for path in binaries:
                # Prebuilt Sparkle helpers can have no spare Mach-O header
                # padding. Only an image with an engine edge needs our rpath.
                if any(mapping.get(dependency) or mapping.get(Path(dependency).name)
                       for dependency in dependencies(path)):
                    relocate(path, products, mapping, final_path=destination / path.relative_to(framework))
                for dependency in dependencies(path):
                    replacement = mapping.get(dependency) or mapping.get(Path(dependency).name)
                    if replacement:
                        if dependency != replacement or not (products / replacement.removeprefix("@rpath/")).is_file():
                            raise ValueError(f"Unresolved Sparkle engine dependency: {dependency}")
                    elif dependency.startswith("/System/Library/") and any(name in dependency for name in REQUIRED):
                        raise ValueError(f"System WebKit dependency in Sparkle: {dependency}")
            sign(stage)
        subprocess.run(["codesign", "--verify", "--deep", "--strict", str(framework)], check=True)
        previous = stage / "previous-Sparkle.framework"
        if destination.exists() or destination.is_symlink():
            destination.rename(previous)
        try:
            framework.rename(destination)
        except OSError:
            if previous.exists() or previous.is_symlink():
                previous.rename(destination)
            raise
    mode = "original system development" if system else "Quartz WebKit"
    print(f"Prepared Sparkle for {mode} in {destination}")


def prepare(args):
    build = args.build_dir.resolve()
    output = args.output_dir.resolve()
    for other in (build, args.source_dir.resolve()):
        if output.is_relative_to(other) or other.is_relative_to(output):
            raise ValueError("WebKit output must not overlap the source or raw build directory")
    check_output(args.output_dir)
    lock = json.loads(args.lock_file.read_text())
    if lock["repository"] != REPOSITORY or run("git", "-C", args.source_dir, "rev-parse", "HEAD") != lock["revision"]:
        raise ValueError("Engine source revision does not match the pinned Quartz fork")
    if run("git", "-C", args.source_dir, "status", "--porcelain", "--untracked-files=no"):
        raise ValueError("Refusing to label modified WebKit sources as the pinned revision")
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="webkit-stage-", dir=output.parent) as temporary:
        stage = Path(temporary) / "products"
        stage.mkdir()
        entries = sorted(path for path in build.iterdir() if path.suffix in (".framework", ".xpc", ".dylib"))
        if not entries:
            raise ValueError(f"No WebKit products in {build}")
        for path in entries:
            if path.is_symlink():
                (stage / path.name).symlink_to(os.readlink(path))
            elif path.is_dir():
                shutil.copytree(path, stage / path.name, symlinks=True)
            else:
                shutil.copy2(path, stage / path.name)
        # Xcode can emit absolute symlinks into the same build products. Convert
        # those to relative links, leaving sibling XPC and dylib links intact.
        for path in stage.rglob("*"):
            if path.is_symlink() and os.path.isabs(os.readlink(path)):
                target = Path(os.readlink(path))
                if not target.is_relative_to(build):
                    raise ValueError(f"External product symlink: {path} -> {target}")
                path.unlink()
                path.symlink_to(os.path.relpath(stage / target.relative_to(build), path.parent))
        normalize_webcore_frameworks_link(stage)
        check_symlinks(stage)
        mapping = dependency_map(stage)
        binaries = list(macho_files(stage))
        for path in binaries:
            relocate(path, stage, mapping, set_id=True)
        sign(stage)
        minimum = minimum_version(binaries)
        architectures = sorted(set.intersection(*(architecture_set(path) for path in binaries)))
        # Carry the fork's complete license files with the binaries, plus the
        # exact public source revision needed to retrieve corresponding source.
        licenses = stage / "WebKit-Licenses"
        for source in args.source_dir.rglob("*"):
            if source.is_file() and not source.is_symlink() and source.name.lower().startswith(("license", "copying")) and ".git" not in source.parts:
                destination = licenses / source.relative_to(args.source_dir)
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, destination)
        info = dict(repository=lock["repository"], revision=lock["revision"],
                    macOSDeploymentTarget=lock["macOSDeploymentTarget"], minimumSystemVersion=minimum,
                    architectures=architectures, products=[path.name for path in entries],
                    xcode=run("xcodebuild", "-version"), sdk=run("xcrun", "--sdk", "macosx", "--show-sdk-version"),
                    sha256={str(path.relative_to(stage)): digest(path) for path in binaries})
        (stage / MANIFEST).write_text(json.dumps(info, indent=2) + "\n")
        (stage / MANAGED_MARKER).write_text("Generated by Quartz build-webkit.sh\n")
        validate(stage, args.lock_file)
        if output.exists():
            shutil.rmtree(output)
        shutil.move(stage, output)
    print(f"Prepared Quartz WebKit {lock['revision']} in {output}")


def embed(args):
    products = args.products_dir.resolve()
    info = validate(products, archs=args.arch)
    frameworks = args.app_dir.resolve() / "Contents/Frameworks"
    frameworks.mkdir(parents=True, exist_ok=True)
    for name in info["products"]:
        source = products / name
        destination = frameworks / name
        if source.is_symlink():
            destination.symlink_to(os.readlink(source))
        else:
            subprocess.run(["ditto", str(source), str(destination)], check=True)
    resources = args.app_dir / "Contents/Resources"
    shutil.copy2(products / MANIFEST, resources / MANIFEST)
    shutil.copytree(products / "WebKit-Licenses", resources / "WebKit-Licenses", dirs_exist_ok=True)
    executable = args.app_dir / "Contents/MacOS" / args.executable
    relocate(executable, frameworks, dependency_map(frameworks))
    # Validate the engine's dependency graph separately from Sparkle's helpers.
    binaries = [frameworks / path for path in info["sha256"]]
    verify_links(frameworks, [executable, *binaries])
    check_symlinks(frameworks)
    print(info["minimumSystemVersion"])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    stage = sub.add_parser("prepare")
    for name in ("build-dir", "output-dir", "source-dir"):
        stage.add_argument("--" + name, required=True, type=Path)
    stage.add_argument("--lock-file", type=Path, default=ROOT / "WebKit.lock.json")
    sparkle = sub.add_parser("prepare-sparkle")
    for name in ("source-framework", "output-dir"):
        sparkle.add_argument("--" + name, required=True, type=Path)
    engine = sparkle.add_mutually_exclusive_group(required=True)
    engine.add_argument("--products-dir", type=Path)
    engine.add_argument("--system", action="store_true",
                        help="Restore the original signed artifact for explicit system WebKit development")
    sparkle.add_argument("--manifest", type=Path,
                         help="Engine manifest when products are embedded in an app")
    check = sub.add_parser("verify")
    check.add_argument("products_dir", type=Path)
    check.add_argument("--arch", action="append", default=[])
    copy = sub.add_parser("embed")
    copy.add_argument("--products-dir", required=True, type=Path)
    copy.add_argument("--app-dir", required=True, type=Path)
    copy.add_argument("--executable", default="Quartz")
    copy.add_argument("--arch", action="append", default=[])
    signing = sub.add_parser("sign")
    signing.add_argument("directory", type=Path)
    signing.add_argument("--identity", default="-")
    signing.add_argument("--manifest", type=Path,
                         help="Verify and refresh the packaged engine manifest around signing")
    output = sub.add_parser("check-output")
    output.add_argument("directory", type=Path)
    args = parser.parse_args()
    if args.command == "prepare":
        prepare(args)
    elif args.command == "prepare-sparkle":
        prepare_sparkle(args)
    elif args.command == "verify":
        print(json.dumps(validate(args.products_dir, archs=args.arch), indent=2))
    elif args.command == "embed":
        embed(args)
    elif args.command == "check-output":
        check_output(args.directory)
    else:
        sign(args.directory, args.identity, args.manifest)


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, KeyError, subprocess.CalledProcessError) as error:
        sys.exit(f"error: {error}")
